builds:
  - binary: gammaray
    goos:
      - linux
      - windows
    goarch:
      - amd64
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
    - LICENSE
